// Generated by gencpp from file devices/RtkMsg.msg
// DO NOT EDIT!


#ifndef DEVICES_MESSAGE_RTKMSG_H
#define DEVICES_MESSAGE_RTKMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace devices
{
template <class ContainerAllocator>
struct RtkMsg_
{
  typedef RtkMsg_<ContainerAllocator> Type;

  RtkMsg_()
    : header()
    , raw_string()  {
    }
  RtkMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , raw_string(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _raw_string_type;
  _raw_string_type raw_string;





  typedef boost::shared_ptr< ::devices::RtkMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::devices::RtkMsg_<ContainerAllocator> const> ConstPtr;

}; // struct RtkMsg_

typedef ::devices::RtkMsg_<std::allocator<void> > RtkMsg;

typedef boost::shared_ptr< ::devices::RtkMsg > RtkMsgPtr;
typedef boost::shared_ptr< ::devices::RtkMsg const> RtkMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::devices::RtkMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::devices::RtkMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace devices

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'devices': ['/home/nguyen/vio_ws/src/driver/devices/slider/msg', '/home/nguyen/vio_ws/src/driver/devices/span/msg', '/home/nguyen/vio_ws/src/driver/devices/wheel/msg', '/home/nguyen/vio_ws/src/driver/devices/gps/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::devices::RtkMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::devices::RtkMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::devices::RtkMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::devices::RtkMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::devices::RtkMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::devices::RtkMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::devices::RtkMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d09cacb8395420a614d91e15f9502b9d";
  }

  static const char* value(const ::devices::RtkMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd09cacb8395420a6ULL;
  static const uint64_t static_value2 = 0x14d91e15f9502b9dULL;
};

template<class ContainerAllocator>
struct DataType< ::devices::RtkMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "devices/RtkMsg";
  }

  static const char* value(const ::devices::RtkMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::devices::RtkMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message of navigation information read from the SPAN-CPT system (log INSPVAX)\n\
\n\
# Hedaer of this ros message\n\
# header.seq        : consecutive increasing ID\n\
# header.stamp      : timestamp of the message\n\
#   .sec            : seconds\n\
#   .nsec           : nanoseconds\n\
# header.frame_id   : name of this data\n\
Header header\n\
\n\
# Raw string recorded from RTK rover\n\
string raw_string\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::devices::RtkMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::devices::RtkMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.raw_string);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RtkMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::devices::RtkMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::devices::RtkMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "raw_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.raw_string);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEVICES_MESSAGE_RTKMSG_H
