// Generated by gencpp from file devices/SliderMsg.msg
// DO NOT EDIT!


#ifndef DEVICES_MESSAGE_SLIDERMSG_H
#define DEVICES_MESSAGE_SLIDERMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace devices
{
template <class ContainerAllocator>
struct SliderMsg_
{
  typedef SliderMsg_<ContainerAllocator> Type;

  SliderMsg_()
    : header()
    , current_position(0.0)
    , set_position(0.0)  {
    }
  SliderMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , current_position(0.0)
    , set_position(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _current_position_type;
  _current_position_type current_position;

   typedef double _set_position_type;
  _set_position_type set_position;





  typedef boost::shared_ptr< ::devices::SliderMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::devices::SliderMsg_<ContainerAllocator> const> ConstPtr;

}; // struct SliderMsg_

typedef ::devices::SliderMsg_<std::allocator<void> > SliderMsg;

typedef boost::shared_ptr< ::devices::SliderMsg > SliderMsgPtr;
typedef boost::shared_ptr< ::devices::SliderMsg const> SliderMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::devices::SliderMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::devices::SliderMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace devices

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'devices': ['/home/nguyen/vio_ws/src/driver/devices/slider/msg', '/home/nguyen/vio_ws/src/driver/devices/span/msg', '/home/nguyen/vio_ws/src/driver/devices/wheel/msg', '/home/nguyen/vio_ws/src/driver/devices/gps/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::devices::SliderMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::devices::SliderMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::devices::SliderMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::devices::SliderMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::devices::SliderMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::devices::SliderMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::devices::SliderMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80a3b7d98d77f99e273a14e0b8cc28f9";
  }

  static const char* value(const ::devices::SliderMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80a3b7d98d77f99eULL;
  static const uint64_t static_value2 = 0x273a14e0b8cc28f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::devices::SliderMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "devices/SliderMsg";
  }

  static const char* value(const ::devices::SliderMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::devices::SliderMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "### Message type for the slider bar in my VIO project\n\
\n\
# Header contains time stamp, sequence ID and frame ID\n\
Header header\n\
# Data includes:\n\
float64 current_position    # current position of the slider endpoint\n\
float64 set_position        # set position into the slider controller\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::devices::SliderMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::devices::SliderMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.current_position);
      stream.next(m.set_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SliderMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::devices::SliderMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::devices::SliderMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "current_position: ";
    Printer<double>::stream(s, indent + "  ", v.current_position);
    s << indent << "set_position: ";
    Printer<double>::stream(s, indent + "  ", v.set_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEVICES_MESSAGE_SLIDERMSG_H
