// Generated by gencpp from file devices/WheelMsg.msg
// DO NOT EDIT!


#ifndef DEVICES_MESSAGE_WHEELMSG_H
#define DEVICES_MESSAGE_WHEELMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace devices
{
template <class ContainerAllocator>
struct WheelMsg_
{
  typedef WheelMsg_<ContainerAllocator> Type;

  WheelMsg_()
    : header()
    , encoder_velocity_left(0)
    , encoder_velocity_right(0)
    , encoder_position_left(0)
    , encoder_position_right(0)  {
    }
  WheelMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , encoder_velocity_left(0)
    , encoder_velocity_right(0)
    , encoder_position_left(0)
    , encoder_position_right(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _encoder_velocity_left_type;
  _encoder_velocity_left_type encoder_velocity_left;

   typedef int32_t _encoder_velocity_right_type;
  _encoder_velocity_right_type encoder_velocity_right;

   typedef int32_t _encoder_position_left_type;
  _encoder_position_left_type encoder_position_left;

   typedef int32_t _encoder_position_right_type;
  _encoder_position_right_type encoder_position_right;





  typedef boost::shared_ptr< ::devices::WheelMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::devices::WheelMsg_<ContainerAllocator> const> ConstPtr;

}; // struct WheelMsg_

typedef ::devices::WheelMsg_<std::allocator<void> > WheelMsg;

typedef boost::shared_ptr< ::devices::WheelMsg > WheelMsgPtr;
typedef boost::shared_ptr< ::devices::WheelMsg const> WheelMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::devices::WheelMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::devices::WheelMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace devices

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'devices': ['/home/nguyen/vio_ws/src/driver/devices/slider/msg', '/home/nguyen/vio_ws/src/driver/devices/span/msg', '/home/nguyen/vio_ws/src/driver/devices/wheel/msg', '/home/nguyen/vio_ws/src/driver/devices/gps/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::devices::WheelMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::devices::WheelMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::devices::WheelMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::devices::WheelMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::devices::WheelMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::devices::WheelMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::devices::WheelMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1acbf06768b2f4bd68a3ae020bb8446";
  }

  static const char* value(const ::devices::WheelMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1acbf06768b2f4bULL;
  static const uint64_t static_value2 = 0xd68a3ae020bb8446ULL;
};

template<class ContainerAllocator>
struct DataType< ::devices::WheelMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "devices/WheelMsg";
  }

  static const char* value(const ::devices::WheelMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::devices::WheelMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message of information read from the Wheelchair\n\
\n\
# Hedaer of this ros message\n\
# header.seq        : consecutive increasing ID\n\
# header.stamp      : timestamp of the message\n\
#   .sec            : seconds\n\
#   .nsec           : nanoseconds\n\
# header.frame_id   : name of this data\n\
Header header\n\
\n\
int32 encoder_velocity_left     # [pulse/T]\n\
int32 encoder_velocity_right    # [pulse/T]\n\
int32 encoder_position_left     # [pulse]\n\
int32 encoder_position_right    # [pulse]\n\
# float64 wheel_velocity_left     # [m/s]  = encoder_velocity_left  * (f * circum / resol)\n\
# float64 wheel_velocity_right    # [m/s]  = encoder_velocity_right * (f * circum / resol)\n\
# float64 wheel_position_left     # [m]    = encoder_position_left  * (circum / resol)\n\
# float64 wheel_position_right    # [m]    = encoder_position_right * (circum / resol)\n\
\n\
# Encoder resolution: 3200 pulse/round\n\
# Wheel circumference: 1.433 meter\n\
# Sampling frequency (f = 1/T): 100Hz\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::devices::WheelMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::devices::WheelMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.encoder_velocity_left);
      stream.next(m.encoder_velocity_right);
      stream.next(m.encoder_position_left);
      stream.next(m.encoder_position_right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::devices::WheelMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::devices::WheelMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "encoder_velocity_left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.encoder_velocity_left);
    s << indent << "encoder_velocity_right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.encoder_velocity_right);
    s << indent << "encoder_position_left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.encoder_position_left);
    s << indent << "encoder_position_right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.encoder_position_right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEVICES_MESSAGE_WHEELMSG_H
