# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from devices/GpsMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import devices.msg
import geometry_msgs.msg
import std_msgs.msg

class GpsMsg(genpy.Message):
  _md5sum = "f47c7c77f2a7901121e8d2f16bd8f0f5"
  _type = "devices/GpsMsg"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
geometry_msgs/Vector3 latlongheight
geometry_msgs/Vector3 latlongheight_error
geometry_msgs/Vector3 llh_origin
geometry_msgs/Vector3 enu_position
geometry_msgs/Vector3 velocity # <course-over-ground> <speed-over-ground> <up speed>
geometry_msgs/Vector3 velocity_error
GpsStatus status

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: devices/GpsStatus
string date
float64 time
int16 numsat
int16 quality
float64 hdop"""
  __slots__ = ['header','latlongheight','latlongheight_error','llh_origin','enu_position','velocity','velocity_error','status']
  _slot_types = ['std_msgs/Header','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','devices/GpsStatus']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,latlongheight,latlongheight_error,llh_origin,enu_position,velocity,velocity_error,status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GpsMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.latlongheight is None:
        self.latlongheight = geometry_msgs.msg.Vector3()
      if self.latlongheight_error is None:
        self.latlongheight_error = geometry_msgs.msg.Vector3()
      if self.llh_origin is None:
        self.llh_origin = geometry_msgs.msg.Vector3()
      if self.enu_position is None:
        self.enu_position = geometry_msgs.msg.Vector3()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      if self.velocity_error is None:
        self.velocity_error = geometry_msgs.msg.Vector3()
      if self.status is None:
        self.status = devices.msg.GpsStatus()
    else:
      self.header = std_msgs.msg.Header()
      self.latlongheight = geometry_msgs.msg.Vector3()
      self.latlongheight_error = geometry_msgs.msg.Vector3()
      self.llh_origin = geometry_msgs.msg.Vector3()
      self.enu_position = geometry_msgs.msg.Vector3()
      self.velocity = geometry_msgs.msg.Vector3()
      self.velocity_error = geometry_msgs.msg.Vector3()
      self.status = devices.msg.GpsStatus()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18d().pack(_x.latlongheight.x, _x.latlongheight.y, _x.latlongheight.z, _x.latlongheight_error.x, _x.latlongheight_error.y, _x.latlongheight_error.z, _x.llh_origin.x, _x.llh_origin.y, _x.llh_origin.z, _x.enu_position.x, _x.enu_position.y, _x.enu_position.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.velocity_error.x, _x.velocity_error.y, _x.velocity_error.z))
      _x = self.status.date
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d2hd().pack(_x.status.time, _x.status.numsat, _x.status.quality, _x.status.hdop))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.latlongheight is None:
        self.latlongheight = geometry_msgs.msg.Vector3()
      if self.latlongheight_error is None:
        self.latlongheight_error = geometry_msgs.msg.Vector3()
      if self.llh_origin is None:
        self.llh_origin = geometry_msgs.msg.Vector3()
      if self.enu_position is None:
        self.enu_position = geometry_msgs.msg.Vector3()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      if self.velocity_error is None:
        self.velocity_error = geometry_msgs.msg.Vector3()
      if self.status is None:
        self.status = devices.msg.GpsStatus()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 144
      (_x.latlongheight.x, _x.latlongheight.y, _x.latlongheight.z, _x.latlongheight_error.x, _x.latlongheight_error.y, _x.latlongheight_error.z, _x.llh_origin.x, _x.llh_origin.y, _x.llh_origin.z, _x.enu_position.x, _x.enu_position.y, _x.enu_position.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.velocity_error.x, _x.velocity_error.y, _x.velocity_error.z,) = _get_struct_18d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.date = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status.date = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.status.time, _x.status.numsat, _x.status.quality, _x.status.hdop,) = _get_struct_d2hd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18d().pack(_x.latlongheight.x, _x.latlongheight.y, _x.latlongheight.z, _x.latlongheight_error.x, _x.latlongheight_error.y, _x.latlongheight_error.z, _x.llh_origin.x, _x.llh_origin.y, _x.llh_origin.z, _x.enu_position.x, _x.enu_position.y, _x.enu_position.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.velocity_error.x, _x.velocity_error.y, _x.velocity_error.z))
      _x = self.status.date
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d2hd().pack(_x.status.time, _x.status.numsat, _x.status.quality, _x.status.hdop))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.latlongheight is None:
        self.latlongheight = geometry_msgs.msg.Vector3()
      if self.latlongheight_error is None:
        self.latlongheight_error = geometry_msgs.msg.Vector3()
      if self.llh_origin is None:
        self.llh_origin = geometry_msgs.msg.Vector3()
      if self.enu_position is None:
        self.enu_position = geometry_msgs.msg.Vector3()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      if self.velocity_error is None:
        self.velocity_error = geometry_msgs.msg.Vector3()
      if self.status is None:
        self.status = devices.msg.GpsStatus()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 144
      (_x.latlongheight.x, _x.latlongheight.y, _x.latlongheight.z, _x.latlongheight_error.x, _x.latlongheight_error.y, _x.latlongheight_error.z, _x.llh_origin.x, _x.llh_origin.y, _x.llh_origin.z, _x.enu_position.x, _x.enu_position.y, _x.enu_position.z, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.velocity_error.x, _x.velocity_error.y, _x.velocity_error.z,) = _get_struct_18d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status.date = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status.date = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.status.time, _x.status.numsat, _x.status.quality, _x.status.hdop,) = _get_struct_d2hd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_18d = None
def _get_struct_18d():
    global _struct_18d
    if _struct_18d is None:
        _struct_18d = struct.Struct("<18d")
    return _struct_18d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_d2hd = None
def _get_struct_d2hd():
    global _struct_d2hd
    if _struct_d2hd is None:
        _struct_d2hd = struct.Struct("<d2hd")
    return _struct_d2hd
